# Generated by Django 4.1 on 2022-08-04 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=20)),
                ('category_id', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=500)),
                ('type', models.CharField(max_length=30)),
                ('media_url', models.URLField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ContentCategory', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='content.contentcategory')),
            ],
        ),
    ]
