# Generated by Django 4.1 on 2022-08-05 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contenttype',
            options={'ordering': ()},
        ),
        migrations.RemoveField(
            model_name='contentcategory',
            name='id',
        ),
        migrations.RemoveField(
            model_name='contenttype',
            name='id',
        ),
        migrations.AddField(
            model_name='contenttype',
            name='content_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contentcategory',
            name='category_id',
            field=models.IntegerField(primary_key=b'I01\n', serialize=False),
        ),
        migrations.AlterField(
            model_name='contentcategory',
            name='category_name',
            field=models.CharField(choices=[('fireside', 'fireside'), ('ptow', 'ptow'), ('articles', 'articles')], max_length=20),
        ),
    ]
