# Generated by Django 4.1 on 2022-08-05 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_contenttype_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contenttype',
            name='thumbnail',
        ),
    ]
